---
- name: Create victoriametrics vmstorage directory
  ansible.builtin.file:
    path: "{{ victoriametrics_cluster_vmstorage_storage_data_path }}"
    state: directory
    owner: "{{ victoriametrics_cluster_user }}"
    group: "{{ victoriametrics_cluster_user }}"
    mode: "0755"
  when: victoriametrics_cluster_vmstorage

- name: Download victoriametrics cluster files
  become: false
  ansible.builtin.get_url:
    url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_cluster_version }}/victoria-metrics-{{ ansible_system | lower }}-{{
      victoriametrics_arch }}-v{{ victoriametrics_cluster_version }}-cluster.tar.gz
    dest: /tmp/
    mode: "0755"
  delegate_to: localhost

- name: Create temporary directory
  become: false
  ansible.builtin.file:
    path: /tmp/victoriametrics_cluster_{{ victoriametrics_cluster_version }}_{{ victoriametrics_arch }}
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Unarchive victoriametrics cluster files
  become: false
  ansible.builtin.unarchive:
    src: /tmp/victoria-metrics-{{ ansible_system | lower }}-{{ victoriametrics_arch }}-v{{ victoriametrics_cluster_version }}-cluster.tar.gz
    remote_src: true
    dest: /tmp/victoriametrics_cluster_{{ victoriametrics_cluster_version }}_{{ victoriametrics_arch }}/
    creates: /tmp/victoriametrics_cluster_{{ victoriametrics_cluster_version }}_{{ victoriametrics_arch }}/vmselect-prod
  delegate_to: localhost
  check_mode: false

- name: Propagate vminsert binary
  ansible.builtin.copy:
    src: /tmp/victoriametrics_cluster_{{ victoriametrics_cluster_version }}_{{ victoriametrics_arch }}/vminsert-prod
    dest: /usr/local/bin/vminsert
    mode: "0755"
    owner: "{{ victoriametrics_cluster_user }}"
    group: "{{ victoriametrics_cluster_user }}"
  when: victoriametrics_cluster_vminsert and victoriametrics_cluster_vminsert is defined
  notify:
    - Restart vminsert

- name: Propagate vmselect binary
  ansible.builtin.copy:
    src: /tmp/victoriametrics_cluster_{{ victoriametrics_cluster_version }}_{{ victoriametrics_arch }}/vmselect-prod
    dest: /usr/local/bin/vmselect
    mode: "0755"
    owner: "{{ victoriametrics_cluster_user }}"
    group: "{{ victoriametrics_cluster_user }}"
  when: victoriametrics_cluster_vmselect and victoriametrics_cluster_vmselect is defined
  notify:
    - Restart vmselect

- name: Propagate vmstorage binary
  ansible.builtin.copy:
    src: /tmp/victoriametrics_cluster_{{ victoriametrics_cluster_version }}_{{ victoriametrics_arch }}/vmstorage-prod
    dest: /usr/local/bin/vmstorage
    mode: "0755"
    owner: "{{ victoriametrics_cluster_user }}"
    group: "{{ victoriametrics_cluster_user }}"
  when: victoriametrics_cluster_vmstorage and victoriametrics_cluster_vmstorage is defined
  notify:
    - Restart vmstorage

- name: Create vminsert systemd service unit
  ansible.builtin.template:
    src: cluster/vminsert.service.j2
    dest: /etc/systemd/system/vminsert.service
    owner: root
    group: root
    mode: "0644"
  when: victoriametrics_cluster_vminsert and victoriametrics_cluster_vminsert is defined
  notify:
    - Restart vminsert

- name: Create vmselect systemd service unit
  ansible.builtin.template:
    src: cluster/vmselect.service.j2
    dest: /etc/systemd/system/vmselect.service
    owner: root
    group: root
    mode: "0644"
  when: victoriametrics_cluster_vmselect and victoriametrics_cluster_vmselect is defined
  notify:
    - Restart vmselect

- name: Create vminsert systemd service unit
  ansible.builtin.template:
    src: cluster/vmstorage.service.j2
    dest: /etc/systemd/system/vmstorage.service
    owner: root
    group: root
    mode: "0644"
  when: victoriametrics_cluster_vmstorage and victoriametrics_cluster_vmstorage is defined
  notify:
    - Restart vmstorage
