---
- ansible.builtin.import_tasks: user.yml
- ansible.builtin.import_tasks: singlenode.yml
  when: victoriametrics_singlenode and victoriametrics_singlenode is defined
- ansible.builtin.import_tasks: cluster.yml
  when: victoriametrics_cluster and victoriametrics_cluster is defined
- ansible.builtin.import_tasks: vmutils.yml
  when: victoriametrics_vmutils and victoriametrics_vmutils is defined
