---
- name: Create victoriametrics system group
  ansible.builtin.group:
    name: "{{ victoriametrics_user }}"
    system: true
    state: present

- name: Create victoriametrics system user
  ansible.builtin.user:
    name: "{{ victoriametrics_user }}"
    system: true
    shell: /usr/sbin/nologin
    group: "{{ victoriametrics_user }}"
    createhome: false
