# handlers file for VictoriaMetrics
---
- name: Restart vmselect
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmselect
    state: restarted
    enabled: true

- name: Restart vminsert
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vminsert
    state: restarted
    enabled: true

- name: Restart vmstorage
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmstorage
    state: restarted
    enabled: true

- name: Restart victoriametrics
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
    enabled: true

- name: Restart vmauth
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmauth
    state: restarted
    enabled: true

- name: Restart vmagent
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmagent
    state: restarted
    enabled: true

- name: Restart vmalert
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmalert
    state: restarted
    enabled: true
