# handlers file for VictoriaMetrics
---
- name: Restart vmselect
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmselect
    state: restarted
    enabled: true

- name: Restart vminsert
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vminsert
    state: restarted
    enabled: true

- name: Restart vmstorage
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmstorage
    state: restarted
    enabled: true

- name: Restart victoriametrics
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
    enabled: true

- name: Restart vmauth
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmauth
    state: restarted
    enabled: true

- name: Restart vmagent
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmagent
    state: restarted
    enabled: true

- name: Restart vmalert
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmalert
    state: restarted
    enabled: true

- name: Restart vmestimator
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmestimator
    state: restarted
    enabled: true
  listen: Restart installed vmestimator
  when: victoriametrics_vmestimator | bool

- name: Restart vmestimator-storage
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmestimator-storage
    state: restarted
    enabled: true
  listen: Restart installed vmestimator
  when: victoriametrics_vmestimator_cluster_storage | bool

- name: Restart vmestimator-selector
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vmestimator-selector
    state: restarted
    enabled: true
  listen: Restart installed vmestimator
  when: victoriametrics_vmestimator_cluster_selector | bool
