# handlers file for VictoriaMetrics
---
- name: restart vmselect
  become: true
  systemd:
    daemon_reload: true
    name: vmselect
    state: restarted
    enabled: true

- name: restart vminsert
  become: true
  systemd:
    daemon_reload: true
    name: vminsert
    state: restarted
    enabled: true

- name: restart vmstorage
  become: true
  systemd:
    daemon_reload: true
    name: vmstorage
    state: restarted
    enabled: true

- name: restart victoriametrics
  become: true
  systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
    enabled: true

- name: restart vmauth
  become: true
  systemd:
    daemon_reload: true
    name: vmauth
    state: restarted
    enabled: true

- name: restart vmagent
  become: true
  systemd:
    daemon_reload: true
    name: vmagent
    state: restarted
    enabled: true

- name: restart vmalert
  become: true
  systemd:
    daemon_reload: true
    name: vmalert
    state: restarted
    enabled: true
