---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: victoriametrics
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    diff: true
  env:
    ANSIBLE_ROLES_PATH: ../../../
  inventory:
    group_vars:
      all:
        victoriametrics_singlenode: true
        victoriametrics_singlenode_http_listen_addr: 0.0.0.0:8428
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
