---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vmselect
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: victoriametrics
    groups:
      - victoria_vmselect
  - name: vminsert
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: victoriametrics
    groups:
      - victoria_vminsert
  - name: vmstorage
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: victoriametrics
    groups:
      - victoria_vmstorage
provisioner:
  name: ansible
  options:
    diff: true
  inventory:
    group_vars:
      all:
        victoriametrics_cluster: true
        victoriametrics_vmutils: true
        victoriametrics_cluster_vmstorage_retention_period: 1
        victoriametrics_cluster_vminsert_storage_node:
          - vmstorage:8400
        victoriametrics_cluster_vmselect_storage_node:
          - vmstorage:8401
      victoria_vmselect:
        victoriametrics_cluster_vmselect: true
      victoria_vminsert:
        victoriametrics_cluster_vminsert: true
      victoria_vmstorage:
        victoriametrics_cluster_vmstorage: true
        victoriametrics_cluster_vmstorage_storage_data_path: /var/lib/vmc
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
